name = "toml-glib"
version = "0.1.0"
license = "LGPLv3"
authors = ["Baptiste Gelez <baptiste@gelez.xyz>"]
files = [
  "src/*.vala"
]
repository = "https://framagit.org/Bat/toml-glib.git"
library = true
compiler-params = [
  "-X",
  "--coverage",
]

[scripts]
doc = [
  "valadoc -o doc src/*.vala --pkg gee-0.8 --pkg gio-2.0 --deps"
]
test = [
  "sudo poulp build --install; cd tests; poulp build; ./build/toml-glib-tests"
]
clean = [
  "rm -f src/*.c && rm -f src/*.gcda && rm -f src/*.gcno && rm -rf ./coverage && rm -f coverage.info",
  "cd tests && printf 'Tests: ' && poulp run clean"
]
coverage = [
  "poulp run clean",
  "sudo poulp build --install",
  "cd tests; poulp build; ./build/toml-glib-tests",
  "mv *.gc* src",
  "lcov --capture --directory src --output-file coverage.info",
  "genhtml coverage.info --output-directory coverage"
]
[dependencies]
"gee-0.8" = "*"
"gio-2.0" = "*"

[features]
c-warnings = false
debug = true
